import photosnap from "./images/photosnap.svg";
import manage from "./images/manage.svg";
import account from "./images/account.svg";
import myhome from "./images/myhome.svg";
import loopStudios from "./images/loop-studios.svg";
import faceit from "./images/faceit.svg";
import shortly from "./images/shortly.svg";
import insure from "./images/insure.svg";
import eyecam from "./images/eyecam-co.svg";
import airFilterCompany from "./images/the-air-filter-company.svg";

const Data = [
  {
    id: 1,
    company: "Photosnap",
    logo: photosnap,
    new: true,
    featured: true,
    position: "Senior Frontend Developer",
    postedAt: "1d ago",
    contract: "Full Time",
    location: "USA Only",
    tags: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"],
  },
  {
    id: 2,
    company: "Manage",
    logo: manage,
    new: true,
    featured: true,
    position: "Fullstack Developer",
    postedAt: "1d ago",
    contract: "Part Time",
    location: "Remote",
    tags: ["Fullstack", "Midweight", "Python", "React"],
  },
  {
    id: 3,
    company: "Account",
    logo: account,
    new: true,
    featured: false,
    position: "Junior Frontend Developer",
    postedAt: "2d ago",
    contract: "Part Time",
    location: "USA Only",
    tags: ["Frontend", "Junior", "JavaScript", "React", "Sass"],
  },
  {
    id: 4,
    company: "MyHome",
    logo: myhome,
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    postedAt: "5d ago",
    contract: "Contract",
    location: "USA Only",
    tags: ["Frontend", "Junior", "CSS", "JavaScript"],
  },
  {
    id: 5,
    company: "Loop Studios",
    logo: loopStudios,
    new: false,
    featured: false,
    position: "Software Engineer",
    postedAt: "1w ago",
    contract: "Full Time",
    location: "Worldwide",
    tags: ["Fullstack", "Midweight", "JavaScript", "Ruby", "Sass"],
  },
  {
    id: 6,
    company: "FaceIt",
    logo: faceit,
    new: false,
    featured: false,
    position: "Junior Backend Developer",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "UK Only",
    tags: ["Backend", "Junior", "Ruby", "RoR"],
  },
  {
    id: 7,
    company: "Shortly",
    logo: shortly,
    new: false,
    featured: false,
    position: "Junior Developer",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "Worldwide",
    languages: [],
    tags: ["Frontend", "Junior", "HTML", "JavaScript", "Sass"],
  },
  {
    id: 8,
    company: "Insure",
    logo: insure,
    new: false,
    featured: false,
    position: "Junior Frontend Developer",
    postedAt: "2w ago",
    contract: "Full Time",
    location: "USA Only",
    tags: ["Frontend", "Junior", "JavaScript", "Vue", "Sass"],
  },
  {
    id: 9,
    company: "Eyecam Co.",
    logo: eyecam,
    new: false,
    featured: false,
    position: "Full Stack Engineer",
    postedAt: "3w ago",
    contract: "Full Time",
    location: "Worldwide",
    tags: ["Fullstack", "Midweight", "JavaScript", "Python", "Django"],
  },
  {
    id: 10,
    company: "The Air Filter Company",
    logo: airFilterCompany,
    new: false,
    featured: false,
    position: "Front-end Dev",
    postedAt: "1mo ago",
    contract: "Part Time",
    location: "Worldwide",
    tags: ["Frontend", "Junior", "JavaScript", "React", "Sass"],
  },
];
export default Data;
